# Generated by Django 3.0.5 on 2020-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='nn',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
