# Generated by Django 3.0.5 on 2020-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_paper_nn'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
