# Generated by Django 3.0.5 on 2020-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_paper_paper_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='broker_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='dollar_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='stack_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
